-- SQLBook: Code
CREATE TABLE `SEQUENCE` (
  next INT AUTO_INCREMENT PRIMARY KEY
);


CREATE TABLE `USER_`(
    ID_USER INT PRIMARY KEY AUTO_INCREMENT,
    LAST_CONNECTION DATE DEFAULT NULL,
    ID_ROLE INT,
    USER_PASSWORD VARCHAR(10) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(11) NOT NULL,
    NAME VARCHAR(100) DEFAULT '-',
    DNI VARCHAR(50) DEFAULT NULL,
    CENTER VARCHAR(20) DEFAULT '-',
    EMAIL VARCHAR(50) DEFAULT '-',
    VERIFICATION_CODE VARCHAR(20) DEFAULT '-',
    
);

CREATE TABLE `PROFFESSOR`(
    ID_PROFFERSSOR INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    DATE_OF_HIRE DATE DEFAULT NOW(),
    PROFILE_PHOTO TEXT,
    FOREIGN KEY (ID_USER) REFERENCES USER_(ID_USER)
);

CREATE TABLE `STUDENT`(
    ID_USER INT NOT NULL,
    CAREER VARCHAR(50),
    ID_STUDENT INT PRIMARY KEY AUTO_INCREMENT,  
    YEAR_OF_INCOME DATE DEFAULT NULL,
    STATE VARCHAR(10) DEFAULT 'ACTIVE',
    FOREIGN KEY (ID_USER) REFERENCES USER_(ID_USER)
);

CREATE TABLE `ADMINISTRATOR`(
    ID_ADMINISTRATOR INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    DATE_OF_HIRE DATE DEFAULT NOW(),
    FOREIGN KEY (ID_USER) REFERENCES USER_(ID_USER)
);

CREATE TABLE `PERMISSIONS`(
    ID_PERMISSION INT PRIMARY KEY AUTO_INCREMENT,
    PERMISSION_NAME VARCHAR(20) NOT NULL, 
    PERMISSION_DESCRIPTION VARCHAR(100) NOT NULL
);
CREATE TABLE `ROLE`(
    ID_ROLE INT PRIMARY KEY AUTO_INCREMENT,
    ROLE_NAME VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL
);


CREATE TABLE `ROLE_PERMISSION`(
    ID_ROLE_PERMISSION INT PRIMARY KEY AUTO_INCREMENT,
    ID_ROLE INT NOT NULL,
    ID_PERMISSION INT NOT NULL,
    FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID_ROLE),
    FOREIGN KEY (ID_PERMISSION) REFERENCES PERMISSIONS(ID_PERMISSION)
);

CREATE TABLE `USER_ROLE`(
    ID_USER_ROLE INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT NOT NULL, 
    ID_ROLE INT NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES USER_(ID_USER),
    FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID_ROLE)
);




/*
CREATE TABLE `PERIOD`(

);

CREATE TABLE `COURSE`(

);

CREATE TABLE `BUILDING`(

);

CREATE TABLE `CLASSROOM`(

);

CREATE TABLE `DAY`(


);

CREATE TABLE `ENROLLMENT`(

);

CREATE TABLE `QUALIFICATION`(

);

CREATE TABLE `CAREER`(

);

CREATE TABLE `LABORATORY`(

);

CREATE TABLE `ADMINISTRATOR`(

);

CREATE TABLE `DEAN`(

);

CREATE TABLE `REQUEST`(

);

CREATE TABLE `SECTION`(

);

CREATE TABLE `DEPARTMENT`(

);

CREATE TABLE `PREREQUISITE`(
    
);
*/