USE DATABASE UNIVERSITY;
CREATE TABLE `PERSON`(
    ID_PERSON INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    DNI INT NOT NULL,
    BIRTHDAY DATE NOT NULL,
    GENDER BIT NOT NULL,
    ADDRESS VARCHAR(200),
    PHONE_NUMBER VARCHAR(20),
    EMAIL VARCHAR(20) ,
    NATIONALITY VARCHAR(20)
);

CREATE TABLE `PROFFESSOR`(
    ID_PROFFERSSOR INT PRIMARY KEY AUTO_INCREMENT,
    ID_PERSON INT NOT NULL,
    ID_DEPARTMENT INT NOT NULL,
    ID_TITLE INT NOT NULL,
    ID_SPECIALTY INT NOT NULL, 
    DATE_OF_HIRE DATE NOT NULL
);

CREATE TABLE `STUDENT`(
    ID_STUDENT INT PRIMARY KEY AUTO_INCREMENT,
    ID_PERSON INT NOT NULL,
    YEAR_OF_INCOME DATE NOT NULL,
    STATE VARCHAR(10) NOT NULL

);

CREATE TABLE `ADMINISTRATOR`(
    ID_ADMINISTRATOR INT PRIMARY KEY AUTO_INCREMENT,
    ID_PERSON INT NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    DATE_OF_HIRE DATE NOT NULL,
    ADMIN_ACCOUNT INT NOT NULL,
    ADMIN_PASSWORD VARCHAR(20) NOT NULL
);

CREATE TABLE `PERIOD`(

);

CREATE TABLE `COURSE`(

);

CREATE TABLE `BUILDING`(

);

CREATE TABLE `CLASSROOM`(

);

CREATE TABLE `DAY`(


);

CREATE TABLE `ENROLLMENT`(

);

CREATE TABLE `QUALIFICATION`(

);

CREATE TABLE `CAREER`(

);

CREATE TABLE `LABORATORY`(

);

CREATE TABLE `ADMINISTRATOR`(

);

CREATE TABLE `DEAN`(

);

CREATE TABLE `REQUEST`(

);

CREATE TABLE `SECTION`(

);

CREATE TABLE `DEPARTMENT`(

);

CREATE TABLE `PREREQUISITE`(
    
);